# Generated by Django 4.0.3 on 2022-05-25 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('task_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/')),
                ('dedlayn', models.DateTimeField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='testapp.mentor')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.group')),
            ],
        ),
    ]
