# Generated by Django 4.0.3 on 2022-03-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
